// Morbidity Hub Data — auto-updated by monitor_morbidity.py
// Last updated: 2026-02-27T08:01:31Z

const MORBIDITY_LAST_RUN = "2026-02-27T08:01:31Z";

const MORBIDITY_WATCHLIST = [
    { name: "Barry Gibb", age: 79, preObitStatus: "In Edits" },
    { name: "Berry Gordy", age: 96, preObitStatus: "Pending" },
    { name: "Bill Wyman", age: 89, preObitStatus: "Pending" },
    { name: "Bob Dylan", age: 84, preObitStatus: "Pending" },
    { name: "Brenda Holloway", age: 79, preObitStatus: "Pending" },
    { name: "Brian May", age: 78, preObitStatus: "Pending" },
    { name: "Buddy Guy", age: 89, preObitStatus: "Pending" },
    { name: "Carole Kaye", age: 91, preObitStatus: "Pending" },
    { name: "Diana Ross", age: 82, preObitStatus: "Pending" },
    { name: "Dion", age: 86, preObitStatus: "Pending" },
    { name: "Dr. Dre", age: 61, preObitStatus: "Pending" },
    { name: "Elton John", age: 78, preObitStatus: "Pending" },
    { name: "Eric Clapton", age: 80, preObitStatus: "Pending" },
    { name: "Garth Hudson", age: 88, preObitStatus: "Pending" },
    { name: "George Thorogood", age: 75, preObitStatus: "Pending" },
    { name: "Glenn Hughes", age: 73, preObitStatus: "Pending" },
    { name: "Herb Alpert", age: 91, preObitStatus: "Pending" },
    { name: "Ian Hunter", age: 86, preObitStatus: "In Edits" },
    { name: "Iggy Pop", age: 78, preObitStatus: "Pending" },
    { name: "John Fogerty", age: 80, preObitStatus: "Pending" },
    { name: "Joni Mitchell", age: 82, preObitStatus: "Pending" },
    { name: "Keith Richards", age: 82, preObitStatus: "Pending" },
    { name: "Kenny Burrell", age: 93, preObitStatus: "Pending" },
    { name: "Kim Weston", age: 87, preObitStatus: "Pending" },
    { name: "Klaus Voormann", age: 87, preObitStatus: "Pending" },
    { name: "Manfred Eicher", age: 82, preObitStatus: "Pending" },
    { name: "Marshall Allen", age: 101, preObitStatus: "Pending" },
    { name: "Martha Reeves", age: 84, preObitStatus: "Pending" },
    { name: "Mavis Staples", age: 86, preObitStatus: "Pending" },
    { name: "Mick Jagger", age: 82, preObitStatus: "Pending" },
    { name: "Mike Stoller", age: 93, preObitStatus: "Pending" },
    { name: "Neil Diamond", age: 85, preObitStatus: "Pending" },
    { name: "Ozzy Osbourne", age: 77, preObitStatus: "Pending" },
    { name: "Paul McCartney", age: 83, preObitStatus: "Pending" },
    { name: "Randy Newman", age: 82, preObitStatus: "Pending" },
    { name: "Ray Cooper", age: 79, preObitStatus: "Pending" },
    { name: "Ray Davies", age: 81, preObitStatus: "Pending" },
    { name: "Ringo Starr", age: 85, preObitStatus: "Pending" },
    { name: "Rod Stewart", age: 81, preObitStatus: "Pending" },
    { name: "Roger Daltrey", age: 82, preObitStatus: "Pending" },
    { name: "Ron Carter", age: 88, preObitStatus: "Pending" },
    { name: "Smokey Robinson", age: 86, preObitStatus: "Pending" },
    { name: "Sonny Rollins", age: 95, preObitStatus: "Pending" },
    { name: "Steve Winwood", age: 78, preObitStatus: "Pending" },
    { name: "Tom Waits", age: 76, preObitStatus: "Pending" },
    { name: "Tony Iommi", age: 77, preObitStatus: "Pending" },
    { name: "Wanda Jackson", age: 88, preObitStatus: "Pending" },
    { name: "Willie Nelson", age: 92, preObitStatus: "Pending" },
    { name: "Yoko Ono", age: 93, preObitStatus: "Pending" },
    { name: "Anni-Frid Lyngstad", age: 80, preObitStatus: "Pending" },
    { name: "Barbra Streisand", age: 83, preObitStatus: "Pending" },
    { name: "Benny Andersson", age: 79, preObitStatus: "Pending" },
    { name: "Björn Ulvaeus", age: 80, preObitStatus: "Pending" },
    { name: "Booker T. Jones", age: 81, preObitStatus: "Written" },
    { name: "Donald Fagen", age: 78, preObitStatus: "Pending" },
    { name: "Engelbert Humperdinck", age: 89, preObitStatus: "Pending" },
    { name: "George Clinton", age: 84, preObitStatus: "Pending" },
    { name: "Jerry Butler", age: 86, preObitStatus: "Pending" },
    { name: "John Cale", age: 83, preObitStatus: "Pending" },
    { name: "John Williams", age: 94, preObitStatus: "Written" },
    { name: "Kris Kristofferson", age: 88, preObitStatus: "Pending" },
    { name: "Lalo Schifrin", age: 93, preObitStatus: "Pending" },
    { name: "Patti LaBelle", age: 81, preObitStatus: "Written" },
    { name: "Randy Bachman", age: 82, preObitStatus: "Pending" },
    { name: "Shirley Bassey", age: 89, preObitStatus: "Pending" },
    { name: "Steven Tyler", age: 77, preObitStatus: "Pending" },
    { name: "Richard Davis", age: 96, preObitStatus: "Published" },
];

const MORBIDITY_ALERTS = [
];
