// Morbidity Hub Data — auto-updated by monitor_morbidity.py
// Last updated: 2026-02-22T20:52:03Z

const MORBIDITY_LAST_RUN = "2026-02-22T20:52:03Z";

const MORBIDITY_WATCHLIST = [
    { name: "Barry Gibb", age: 79, preObitStatus: "In Edits" },
    { name: "Berry Gordy", age: 96, preObitStatus: "Pending" },
    { name: "Bill Wyman", age: 89, preObitStatus: "Pending" },
    { name: "Bob Dylan", age: 84, preObitStatus: "Pending" },
    { name: "Brenda Holloway", age: 79, preObitStatus: "Pending" },
    { name: "Brian May", age: 78, preObitStatus: "Pending" },
    { name: "Buddy Guy", age: 89, preObitStatus: "Pending" },
    { name: "Carole Kaye", age: 91, preObitStatus: "Pending" },
    { name: "Diana Ross", age: 82, preObitStatus: "Pending" },
    { name: "Dion", age: 86, preObitStatus: "Pending" },
    { name: "Dr. Dre", age: 61, preObitStatus: "Pending" },
    { name: "Elton John", age: 78, preObitStatus: "Pending" },
    { name: "Eric Clapton", age: 80, preObitStatus: "Pending" },
    { name: "Garth Hudson", age: 88, preObitStatus: "Pending" },
    { name: "George Thorogood", age: 75, preObitStatus: "Pending" },
    { name: "Glenn Hughes", age: 73, preObitStatus: "Pending" },
    { name: "Herb Alpert", age: 91, preObitStatus: "Pending" },
    { name: "Ian Hunter", age: 86, preObitStatus: "In Edits" },
    { name: "Iggy Pop", age: 78, preObitStatus: "Pending" },
    { name: "John Fogerty", age: 80, preObitStatus: "Pending" },
    { name: "Joni Mitchell", age: 82, preObitStatus: "Pending" },
    { name: "Keith Richards", age: 82, preObitStatus: "Pending" },
    { name: "Kenny Burrell", age: 93, preObitStatus: "Pending" },
    { name: "Kim Weston", age: 87, preObitStatus: "Pending" },
    { name: "Klaus Voormann", age: 87, preObitStatus: "Pending" },
    { name: "Manfred Eicher", age: 82, preObitStatus: "Pending" },
    { name: "Marshall Allen", age: 101, preObitStatus: "Pending" },
    { name: "Martha Reeves", age: 84, preObitStatus: "Pending" },
    { name: "Mavis Staples", age: 86, preObitStatus: "Pending" },
    { name: "Mick Jagger", age: 82, preObitStatus: "Pending" },
    { name: "Mike Stoller", age: 93, preObitStatus: "Pending" },
    { name: "Neil Diamond", age: 85, preObitStatus: "Pending" },
    { name: "Ozzy Osbourne", age: 77, preObitStatus: "Pending" },
    { name: "Paul McCartney", age: 83, preObitStatus: "Pending" },
    { name: "Randy Newman", age: 82, preObitStatus: "Pending" },
    { name: "Ray Cooper", age: 79, preObitStatus: "Pending" },
    { name: "Ray Davies", age: 81, preObitStatus: "Pending" },
    { name: "Ringo Starr", age: 85, preObitStatus: "Pending" },
    { name: "Rod Stewart", age: 81, preObitStatus: "Pending" },
    { name: "Roger Daltrey", age: 82, preObitStatus: "Pending" },
    { name: "Ron Carter", age: 88, preObitStatus: "Pending" },
    { name: "Smokey Robinson", age: 86, preObitStatus: "Pending" },
    { name: "Sonny Rollins", age: 95, preObitStatus: "Pending" },
    { name: "Steve Winwood", age: 78, preObitStatus: "Pending" },
    { name: "Tom Waits", age: 76, preObitStatus: "Pending" },
    { name: "Tony Iommi", age: 77, preObitStatus: "Pending" },
    { name: "Wanda Jackson", age: 88, preObitStatus: "Pending" },
    { name: "Willie Nelson", age: 92, preObitStatus: "Pending" },
    { name: "Yoko Ono", age: 93, preObitStatus: "Pending" },
    { name: "Anni-Frid Lyngstad", age: 80, preObitStatus: "Pending" },
    { name: "Barbra Streisand", age: 83, preObitStatus: "Pending" },
    { name: "Benny Andersson", age: 79, preObitStatus: "Pending" },
    { name: "Björn Ulvaeus", age: 80, preObitStatus: "Pending" },
    { name: "Booker T. Jones", age: 81, preObitStatus: "Written" },
    { name: "Donald Fagen", age: 78, preObitStatus: "Pending" },
    { name: "Engelbert Humperdinck", age: 89, preObitStatus: "Pending" },
    { name: "George Clinton", age: 84, preObitStatus: "Pending" },
    { name: "Jerry Butler", age: 86, preObitStatus: "Pending" },
    { name: "John Cale", age: 83, preObitStatus: "Pending" },
    { name: "John Williams", age: 94, preObitStatus: "Written" },
    { name: "Kris Kristofferson", age: 88, preObitStatus: "Pending" },
    { name: "Lalo Schifrin", age: 93, preObitStatus: "Pending" },
    { name: "Patti LaBelle", age: 81, preObitStatus: "Written" },
    { name: "Randy Bachman", age: 82, preObitStatus: "Pending" },
    { name: "Shirley Bassey", age: 89, preObitStatus: "Pending" },
    { name: "Steven Tyler", age: 77, preObitStatus: "Pending" },
    { name: "Richard Davis", age: 96, preObitStatus: "Published" },
];

const MORBIDITY_ALERTS = [
    { date: "2026-02-22", artistName: "Bob Dylan", category: "death", headline: "DAVID MARCUS: Memo to Bono: Please shut up and go away", url: "https://www.foxnews.com/opinion/david-marcus-memo-bono-please-shut-up-go-away", source: "Fox News" },
    { date: "2026-02-22", artistName: "Bob Dylan", category: "death", headline: "Emmylou Harris: ‘It’s a lot harder, isn’t it, to just live a long life?’", url: "https://www.the-independent.com/arts-entertainment/music/features/emmylou-harris-interview-tour-uk-albert-hall-b2922802.html", source: "The-independent.com" },
    { date: "2026-02-22", artistName: "Bob Dylan", category: "death", headline: "Nicolas Cage Is a Vampire? The Truth Behind Viral Celebrity Doppelgänger Conspiracies", url: "https://www.joblo.com/nicolas-cage-is-a-vampire/", source: "JoBlo.com" },
    { date: "2026-02-22", artistName: "Bob Dylan", category: "death", headline: "Ben Vaughn tried explaining the Jerry Blavat phenomenon on the latest episode of his new podcast", url: "https://www.inquirer.com/entertainment/music/ben-vaughn-jerry-blavat-straight-from-the-hat-podcast-20260220.html", source: "The Philadelphia Inquirer" },
    { date: "2026-02-22", artistName: "Diana Ross", category: "death", headline: "Every Movie and TV Show Coming to Peacock in March 2026", url: "http://comicbook.com/tv-shows/news/every-movie-and-tv-show-coming-to-peacock-in-march-2026/", source: "ComicBook.com" },
    { date: "2026-02-22", artistName: "Dion", category: "death", headline: "Manipur man races bullets & storms to save sparrows with Rs 5 solution; installs 600 nests, distributes 300 free", url: "https://timesofindia.indiatimes.com/city/guwahati/manipur-man-races-bullets-storms-to-save-sparrows-with-rs-5-solution-installs-600-nests-distributes-300-free/articleshow/128584510.cms", source: "The Times of India" },
    { date: "2026-02-22", artistName: "Dion", category: "death", headline: "Delhi police arrest Bobby Kabootar’s aide linked to Lawrence Bishnoi network", url: "https://timesofindia.indiatimes.com/city/delhi/delhi-police-arrest-bobby-kabootars-aide-linked-to-lawrence-bishnoi-network/articleshow/128584609.cms", source: "The Times of India" },
    { date: "2026-02-22", artistName: "Dion", category: "death", headline: "Unnao rape survivor’s death penalty plea: Delhi HC seeks Kuldeep Sengar’s stand", url: "https://timesofindia.indiatimes.com/city/delhi/unnao-rape-survivors-death-penalty-plea-hc-seeks-kuldeep-sengars-stand/articleshow/128584261.cms", source: "The Times of India" },
    { date: "2026-02-22", artistName: "Dr. Dre", category: "death", headline: "Busta Rhymes & J Dilla Dropping New Album ‘Dillagence 2’", url: "http://hiphopdx.com/news/busta-rymes-j-dilla-album-dillagence-2/", source: "HipHopDX" },
    { date: "2026-02-22", artistName: "Elton John", category: "death", headline: "This Is Not How You Would Expect To See These Celebrities (45 pics)", url: "https://izismile.com/2026/02/21/this_is_not_how_you_would_expect_to_see_these_celebrities_45_pics.html", source: "Izismile.com" },
    { date: "2026-02-22", artistName: "Eric Clapton", category: "death", headline: "Rock Out! Baz Luhrmann’s ‘Elvis Presley In Concert’ Strides Onto Imax Ahead Of National Rollout — Specialty Preview", url: "http://deadline.com/2026/02/indie-films-opening-elvis-presley-in-concert-imax-1236731024/", source: "Deadline" },
    { date: "2026-02-22", artistName: "Herb Alpert", category: "health", headline: "Amy Grant on Making Her First New Album in 13 Years, ‘The Me That Remains,’ After Asking: ‘Am I Doing People a Disservice in My Sixties, Singing Songs From the Perspective of a 30-Year-Old?’ (EXCLUSIVE)", url: "https://variety.com/2026/music/news/amy-grant-new-album-the-me-that-remains-interview-1236668245/", source: "Variety" },
    { date: "2026-02-22", artistName: "Iggy Pop", category: "death", headline: "Jesse Malin’s ‘Silver Manhattan’ Off-Broadway Show Tells the Story of His Comeback From a Devastating Stroke, Framed as a Love Letter to New York and Rock and Roll: Theater Review", url: "https://variety.com/2026/music/reviews/jesse-malin-silver-manhattan-theater-review-1236668559/", source: "Variety" },
    { date: "2026-02-22", artistName: "Joni Mitchell", category: "death", headline: "Female, Nude by Rhiannon Lucy Coslett: A sex-on-the-beach cocktail garnished with a polemic on the female gaze", url: "https://www.irishtimes.com/culture/books/review/2026/02/21/female-nude-by-rhiannon-lucy-coslett-a-sex-on-the-beach-cocktail-garnished-with-a-polemic-on-the-female-gaze/", source: "The Irish Times" },
    { date: "2026-02-22", artistName: "Joni Mitchell", category: "death", headline: "Optimal ADP Clusters: 2B Punts", url: "https://fantasy.fangraphs.com/optimal-adp-clusters-2b-punts/", source: "Fangraphs.com" },
    { date: "2026-02-22", artistName: "Ozzy Osbourne", category: "death", headline: "Irish television has become a theme park of throwbacks and weird vibes", url: "https://www.irishtimes.com/culture/2026/02/21/irish-television-has-become-a-theme-park-of-throwbacks-and-weird-vibes/", source: "The Irish Times" },
    { date: "2026-02-22", artistName: "Paul McCartney", category: "death", headline: "Se astros da música mudassem de gênero (musical)", url: "https://www.treta.com.br/se-astros-da-musica-mudassem-de-genero-musical/", source: "Treta.com.br" },
    { date: "2026-02-22", artistName: "Paul McCartney", category: "death", headline: "Quote of the Day by John Lennon: 'All we are saying is give peace a chance…'—Inspiring quotes by the co-lead vocalist of the Beatles", url: "https://economictimes.indiatimes.com/news/international/us/quote-of-the-day-by-john-lennon-all-we-are-saying-is-give-peace-a-chanceinspiring-quotes-by-the-co-lead-vocalist-of-the-beatles/articleshow/128614110.cms", source: "The Times of India" },
    { date: "2026-02-22", artistName: "Paul McCartney", category: "death", headline: "Top analyst says Prince Andrew's arrest could force King Charles to consider stepping aside", url: "https://economictimes.indiatimes.com/news/international/us/top-analyst-says-prince-andrews-arrest-could-force-king-charles-to-consider-stepping-aside/articleshow/128606937.cms", source: "The Times of India" },
];

const MORBIDITY_CONSIDER = [
    { name: "Paul Simon", age: 84, desc: "Simon & Garfunkel, Graceland" },
    { name: "Art Garfunkel", age: 84, desc: "Simon & Garfunkel" },
    { name: "Carole King", age: 83, desc: "Tapestry, Brill Building legend" },
    { name: "Roger Waters", age: 82, desc: "Pink Floyd co-founder" },
    { name: "Jimmy Page", age: 82, desc: "Led Zeppelin founder" },
    { name: "Neil Young", age: 80, desc: "Harvest, CSNY" },
    { name: "Van Morrison", age: 80, desc: "Moondance, Astral Weeks" },
    { name: "Pete Townshend", age: 80, desc: "The Who, Tommy" },
    { name: "Bob Seger", age: 80, desc: "Night Moves, Silver Bullet Band" },
    { name: "Debbie Harry", age: 80, desc: "Blondie, Heart of Glass" },
    { name: "Dionne Warwick", age: 85, desc: "Walk On By, Bacharach interpreter" },
    { name: "Gladys Knight", age: 81, desc: "Midnight Train to Georgia" },
    { name: "Herbie Hancock", age: 85, desc: "Head Hunters, Miles Davis quintet" },
    { name: "Joan Baez", age: 85, desc: "Folk legend, civil rights activist" },
    { name: "Judy Collins", age: 86, desc: "Both Sides Now, folk icon" },
    { name: "Johnny Mathis", age: 90, desc: "Misty, best-selling vocalist" },
    { name: "Bobby Vinton", age: 90, desc: "Blue Velvet" },
    { name: "Frankie Valli", age: 91, desc: "Four Seasons, falsetto icon" },
    { name: "Paul Anka", age: 84, desc: "Diana, wrote My Way" },
    { name: "Tom Jones", age: 85, desc: "It's Not Unusual" },
    { name: "Frankie Avalon", age: 85, desc: "Venus, teen idol" },
    { name: "Jose Feliciano", age: 80, desc: "Feliz Navidad, Light My Fire" },
    { name: "Anne Murray", age: 80, desc: "Snowbird, Canadian icon" },
    { name: "Graham Nash", age: 83, desc: "The Hollies, CSNY" },
    { name: "Stephen Stills", age: 81, desc: "Buffalo Springfield, CSNY" },
    { name: "Bobby Rush", age: 92, desc: "Blues, King of the Chitlin' Circuit" },
    { name: "Zubin Mehta", age: 89, desc: "Conductor, NY/LA Philharmonic" },
    { name: "John McVie", age: 80, desc: "Fleetwood Mac bassist" },
    { name: "Irma Thomas", age: 85, desc: "Soul Queen of New Orleans" },
    { name: "Bill Anderson", age: 88, desc: "Country, Grand Ole Opry legend" },
    { name: "Clive Davis", age: 93, desc: "Columbia/Arista head, signed Springsteen & Whitney" },
    { name: "Chris Blackwell", age: 88, desc: "Island Records founder, launched Bob Marley" },
    { name: "Jac Holzman", age: 94, desc: "Elektra Records founder, signed The Doors" },
    { name: "David Geffen", age: 82, desc: "Asylum/Geffen Records, Eagles, Nirvana" },
    { name: "Bones Howe", age: 92, desc: "Producer for Tom Waits, 5th Dimension" },
    { name: "Eddie Kramer", age: 83, desc: "Engineer for Hendrix, Led Zeppelin" },
    { name: "Glyn Johns", age: 84, desc: "Engineer/producer, Stones, Who, Eagles" },
    { name: "Giorgio Moroder", age: 85, desc: "Electronic music pioneer, Donna Summer" },
    { name: "Brian Holland", age: 84, desc: "Holland-Dozier-Holland, Motown hitmaker" },
    { name: "Eddie Holland", age: 86, desc: "Holland-Dozier-Holland, Motown lyricist" },
    { name: "Kenneth Gamble", age: 82, desc: "Gamble & Huff, Philadelphia soul architect" },
    { name: "Leon Huff", age: 83, desc: "Gamble & Huff, Love Train, O'Jays" },
    { name: "David Porter", age: 84, desc: "Stax songwriter, Soul Man with Isaac Hayes" },
    { name: "Al Kooper", age: 81, desc: "Organ on Like a Rolling Stone, founded BS&T" },
    { name: "Tom Paxton", age: 88, desc: "Folk songwriter, Greenwich Village scene" },
    { name: "Plas Johnson", age: 94, desc: "Pink Panther sax solo, LA session legend" },
    { name: "Don Randi", age: 88, desc: "Wrecking Crew keyboardist, Spector sessions" },
    { name: "Chuck Berghofer", age: 88, desc: "Wrecking Crew bassist, 400+ film soundtracks" },
    { name: "David Hood", age: 82, desc: "Muscle Shoals Rhythm Section bassist" },
    { name: "Norbert Putnam", age: 83, desc: "Muscle Shoals bassist, produced Jimmy Buffett" },
    { name: "Charles Lloyd", age: 87, desc: "Forest Flower, jazz-rock bridge" },
    { name: "Gary Bartz", age: 85, desc: "Miles Davis Live-Evil era, NEA Jazz Master" },
    { name: "Kenny Barron", age: 82, desc: "Jazz pianist, played with Dizzy Gillespie" },
    { name: "Terry Gibbs", age: 101, desc: "Bebop vibraphonist, oldest living jazz musician" },
    { name: "Julian Priester", age: 90, desc: "Trombonist, Sun Ra, Hancock's Mwandishi" },
    { name: "Joe Chambers", age: 83, desc: "Blue Note drummer, Bobby Hutcherson sessions" },
    { name: "Charles Tolliver", age: 83, desc: "Trumpeter, co-founded Strata-East Records" },
    { name: "Buster Williams", age: 83, desc: "Jazz bassist, Hancock's Mwandishi" },
    { name: "Harold Wheeler", age: 82, desc: "Broadway orchestrator, DWTS musical director" },
    { name: "Clarence Carter", age: 89, desc: "Soul singer, Patches, Alabama soul legend" },
    { name: "Phil Balsley", age: 86, desc: "Statler Brothers, Country Music Hall of Fame" },
    { name: "Gyorgy Kurtag", age: 100, desc: "Hungarian composer, living classical legend" },
    { name: "Daniel Barenboim", age: 83, desc: "Pianist/conductor, Berlin State Opera" },
    { name: "Riccardo Muti", age: 84, desc: "Conductor, La Scala, Chicago Symphony" },
    { name: "Neeme Jarvi", age: 88, desc: "Estonian conductor, 500+ albums recorded" },
    { name: "Tom Rush", age: 84, desc: "Folk, early champion of Joni Mitchell" },
    { name: "Steve Miller", age: 82, desc: "Steve Miller Band, Fly Like an Eagle" },
    { name: "Petula Clark", age: 93, desc: "Downtown, British pop legend" },
    { name: "Pat Boone", age: 91, desc: "1950s pop, Love Letters in the Sand" },
    { name: "Chubby Checker", age: 84, desc: "The Twist, dance craze originator" },
];
